(add-to-list 'load-path "~/.emacs.d/rc")

(load "emacs-rc-decor.el")
(load "emacs-rc-encoding.el")
(load "emacs-rc-cua.el")
(load "emacs-rc-syntax.el")
(load "emacs-rc-scroll.el")
(load "emacs-rc-elpa.el")
(load "emacs-rc-colorscheme.el")
(load "emacs-rc-bell.el")
(load "emacs-rc-kill-buffers.el")
(load "emacs-rc-minibuffer.el")
(load "emacs-rc-clojure.el")
(load "emacs-rc-parens.el")
(load "emacs-rc-keys.el")
(load "emacs-rc-indent.el")
(load "emacs-rc-indent-cc.el")
(load "emacs-rc-indent-clojure.el")
(load "emacs-rc-windmove.el")
(load "emacs-rc-slime.el")
(load "emacs-rc-autocomplete.el")
(load "emacs-rc-ido.el")
(load "emacs-rc-smex.el")
(load "emacs-rc-project.el")

(setq custom-file "~/.emacs.d/.emacs-custom.el")
(load custom-file)
